apiVersion: apps/v1
kind: Deployment
metadata:
  name: detoxipy-server
  labels:
    deployment: detoxipy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: detoxipy-server
  template:
    metadata:
      labels:
        pod: detoxipy-server
    spec:
      containers:
        - name: detoxipy-server
          image: detoxipy:0.0.1
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POSTGRES_HOST
              value: postgres-service

            - name: REDIS_HOST
              value: redis-service
