kind: Service
apiVersion: v1
metadata:
    name: detoxipy-server-service
spec:
    selector:
        pod: detoxipy-server
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
    type: NodePort
